repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.14.0
    hooks:
      - id: eslint
        args: [--fix]
